# -*- coding: utf-8 -*-
"""CHATBOT Memo (pattern matching techniques).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Pz0ShlScbhd35SqNvoVq81qdKa-G-DI
"""

import re
import random
# patterns to responses
responses = {
    r'\b(hello|hi)\b': ["Hello! How can I help you?", "Hi there! What can I do for you?"],
    r'\b(how are you|how are you doing)\b': ["I'm just a bot, but I'm here to assist you!", "I'm good, thank you. How can I help?"],
    r'\b(goodbye|bye)\b': ["Goodbye! Have a great day!", "Bye! Come back soon."],
    r'\b(thanks|thank you)\b': ["You're welcome!", "Glad to help!"],
    r'\b(weather)\b': ["The weather looks good today.", "I'm still in the development stage now, You can check the weather online."],
    r'\b(time)\b': [ "I'm still in the development stage now,But You can check the time on your device."],
    r'\b(age|old )\b': ["I'm a computer program, so I don't have an age.", "I came into existence recently!"],
    r'\b(name)\b': ["I'm a chatbot! You can call me Memo.", "I'm your friendly chatbot Memo here to assist you!"],
    r'\b(how can I help you)\b': ["You can ask me anything or tell me what you need assistance with."],
    r'\b(jokes|joke)\b': ["Why couldn't the bicycle stand up by itself? Because it was two-tired!", "I'm reading a book on anti-gravity. It's impossible to put down!"],
    r'\b(what is your purpose)\b': ["I'm here to assist and answer your questions to the best of my ability."],
    r'\b(how do you work)\b': ["I analyze text and respond based on predefined patterns and responses."],
    r'\b(who created you)\b': ["I was created by a developer Name Mahmoud Adel."],
    r'\b(love)\b': ["I'm a chatbot, but I can certainly help with advice or information about love."],
    r'\b(favorite color)\b': ["I don't have eyes, so I don't have a favorite color!"],
    r'\b(who are you)\b': ["I'm Memo a chatbot designed to assist and provide information."],
    r'\b(what can you do)\b': ["I can answer questions, tell jokes, or provide information on various topics."],
    r'\b(technology)\b': ["Technology is advancing rapidly and impacting every aspect of our lives."],
    r'\b(gaming|game)\b': ["Gaming is a popular form of entertainment enjoyed by many people but if like gaming don't play League of Legends ."],
    r'\b(books|book)\b': ["Books are a great source of knowledge and entertainment."],
    r'\b(egypt|egyptian)\b': ["Egypt is an amazing country with a rich history and beautiful landmarks like the pyramids and the Nile River." ],
    r'\b(mahmoud adel)\b': ["Mahmoud Adel is an Ai developer. He is Egyptian, 22 years old, and a graduated from Modern University for Technology and Information."],
}

def chatbot_response(user_input):
    user_input = user_input.lower()
    response = "I'm sorry, I didn't understand . Can you please rephrase or ask something else?"

    for pattern, replies in responses.items():
        if re.search(pattern, user_input):
            response = replies[random.randint(0, len(replies) - 1)]
            break

    return response

# Example
print("Chatbot(Memo): Hello! How can I assist you today?")
while True:
    user_input = input("You: ")
    response = chatbot_response(user_input)
    print("Memo:", response)
    if re.search(r'\b(goodbye|bye)\b', user_input):
        break